version: "3.7"
services:
  jenkins:
    image: vmtribunalimg:5000/jenkins-tribunal:latest
    deploy:
      placement:
        constraints:
          - node.hotname == VMADMTRB02
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 5G
    ports:
      - 8088:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins:/var/jenkins_home
    networks:
      - KURIER
    environment:
      TZ: "America/Recife"

volumes:
  jenkins:
    local: true

networks:
   KURIER:
     local: true 

